In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mpt
import seaborn as sns
%matplotlib inline

In [3]:
df=pd.read_csv("../BOBdataset/train.csv")
df.head().T

,0,1,2,3,4
ID,65087372,1450153,1969101,6651430,14354669
Loan Amount,10000,3609,28276,11170,16890
Funded Amount,32236,11940,9311,6954,13226
Funded Amount Investor,12329.36286,12191.99692,21603.22455,17877.15585,13539.92667
Term,59,59,59,59,59
Batch Enrolled,BAT2522922,BAT1586599,BAT2136391,BAT2428731,BAT5341619
Interest Rate,11.135007,12.237563,12.545884,16.731201,15.0083
Grade,B,C,F,C,C
Sub Grade,C4,D3,D4,C3,D4
Employment Duration,MORTGAGE,RENT,MORTGAGE,MORTGAGE,MORTGAGE
Home Ownership,176346.6267,39833.921,91506.69105,108286.5759,44234.82545
Verification Status,Not Verified,Source Verified,Source Verified,Source Verified,Source Verified
Payment Plan,n,n,n,n,n
Loan Title,Debt Consolidation,Debt consolidation,Debt Consolidation,Debt consolidation,Credit card refinancing
Debit to Income,16.284758,15.412409,28.137619,18.04373,17.209886
Delinquency - two years,1,0,0,1,1
Inquires - six months,0,0,0,0,3
Open Account,13,12,14,7,13
Public Record,0,0,0,0,1
Revolving Balance,24246,812,1843,13819,1544
Revolving Utilities,74.932551,78.297186,2.07304,67.467951,85.250761
Total Accounts,7,13,20,12,22
Initial List Status,w,f,w,w,w
Total Received Interest,2929.646315,772.769385,863.324396,288.173196,129.239553
Total Received Late Fee,0.102055,0.036181,18.77866,0.044131,19.306646
Recoveries,2.498291,2.377215,4.316277,0.10702,1294.818751
Collection Recovery Fee,0.793724,0.974821,1.020075,0.749971,0.368953
Collection 12 months Medical,0,0,0,0,0
Application Type,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL
Last week Pay,49,109,66,39,18
Accounts Delinquent,0,0,0,0,0
Total Collection Amount,31,53,34,40,430
Total Current Balance,311301,182610,89801,9189,126029
Total Revolving Credit Limit,6619,20885,26155,60214,22579
Loan Status,0,0,0,0,0

In [4]:
df.columns

Index(['ID', 'Loan Amount', 'Funded Amount', 'Funded Amount Investor', 'Term',
       'Batch Enrolled', 'Interest Rate', 'Grade', 'Sub Grade',
       'Employment Duration', 'Home Ownership', 'Verification Status',
       'Payment Plan', 'Loan Title', 'Debit to Income',
       'Delinquency - two years', 'Inquires - six months', 'Open Account',
       'Public Record', 'Revolving Balance', 'Revolving Utilities',
       'Total Accounts', 'Initial List Status', 'Total Received Interest',
       'Total Received Late Fee', 'Recoveries', 'Collection Recovery Fee',
       'Collection 12 months Medical', 'Application Type', 'Last week Pay',
       'Accounts Delinquent', 'Total Collection Amount',
       'Total Current Balance', 'Total Revolving Credit Limit', 'Loan Status'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67463 entries, 0 to 67462
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            67463 non-null  int64
 1   Loan Amount                   67463 non-null  int64
 2   Funded Amount                 67463 non-null  int64
 3   Funded Amount Investor        67463 non-null  float64
 4   Term                          67463 non-null  int64
 5   Batch Enrolled                67463 non-null  object
 6   Interest Rate                 67463 non-null  float64
 7   Grade                         67463 non-null  object
 8   Sub Grade                     67463 non-null  object
 9   Employment Duration           67463 non-null  object
 10  Home Ownership                67463 non-null  float64
 11  Verification Status           67463 non-null  object
 12  Payment Plan                  67463 non-null  object
 13  Loan Title                    67463 non-null  object
 14  Debit to Income               67463 non-null  float64
 15  Delinquency - two years       67463 non-null  int64
 16  Inquires - six months         67463 non-null  int64
 17  Open Account                  67463 non-null  int64
 18  Public Record                 67463 non-null  int64
 19  Revolving Balance             67463 non-null  int64
 20  Revolving Utilities           67463 non-null  float64
 21  Total Accounts                67463 non-null  int64
 22  Initial List Status           67463 non-null  object
 23  Total Received Interest       67463 non-null  float64
 24  Total Received Late Fee       67463 non-null  float64
 25  Recoveries                    67463 non-null  float64
 26  Collection Recovery Fee       67463 non-null  float64
 27  Collection 12 months Medical  67463 non-null  int64
 28  Application Type              67463 non-null  object
 29  Last week Pay                 67463 non-null  int64
 30  Accounts Delinquent           67463 non-null  int64
 31  Total Collection Amount       67463 non-null  int64
 32  Total Current Balance         67463 non-null  int64
 33  Total Revolving Credit Limit  67463 non-null  int64
 34  Loan Status                   67463 non-null  int64
dtypes: float64(9), int64(17), object(9)
memory usage: 18.0+ MB

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,67463.0,2.562761e+07,2.109155e+07,1.297933e+06,6.570288e+06,1.791565e+07,4.271521e+07,7.224578e+07
Loan Amount,67463.0,1.684890e+04,8.367866e+03,1.014000e+03,1.001200e+04,1.607300e+04,2.210600e+04,3.500000e+04
Funded Amount,67463.0,1.577060e+04,8.150993e+03,1.014000e+03,9.266500e+03,1.304200e+04,2.179300e+04,3.499900e+04
Funded Amount Investor,67463.0,1.462180e+04,6.785345e+03,1.114590e+03,9.831685e+03,1.279368e+04,1.780759e+04,3.499975e+04
Term,67463.0,5.817381e+01,3.327441e+00,3.600000e+01,5.800000e+01,5.900000e+01,5.900000e+01,5.900000e+01
Interest Rate,67463.0,1.184626e+01,3.718629e+00,5.320006e+00,9.297147e+00,1.137770e+01,1.419353e+01,2.718235e+01
Home Ownership,67463.0,8.054150e+04,4.502912e+04,1.457354e+04,5.168984e+04,6.933583e+04,9.462332e+04,4.065615e+05
Debit to Income,67463.0,2.329924e+01,8.451824e+00,6.752991e-01,1.675642e+01,2.265666e+01,3.004840e+01,3.962986e+01
Delinquency - two years,67463.0,3.271275e-01,8.008884e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.000000e+00
Inquires - six months,67463.0,1.457540e-01,4.732913e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00
Open Account,67463.0,1.426656e+01,6.225060e+00,2.000000e+00,1.000000e+01,1.300000e+01,1.600000e+01,3.700000e+01
Public Record,67463.0,8.143723e-02,3.466057e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
Revolving Balance,67463.0,7.699342e+03,7.836148e+03,0.000000e+00,2.557000e+03,5.516000e+03,1.018450e+04,1.169330e+05
Revolving Utilities,67463.0,5.288944e+01,2.253945e+01,5.172360e-03,3.865882e+01,5.408233e+01,6.917712e+01,1.008800e+02
Total Accounts,67463.0,1.862793e+01,8.319246e+00,4.000000e+00,1.300000e+01,1.800000e+01,2.300000e+01,7.200000e+01
Total Received Interest,67463.0,2.068993e+03,2.221919e+03,4.736746e+00,5.709038e+02,1.330843e+03,2.656957e+03,1.430137e+04
Total Received Late Fee,67463.0,1.143969e+00,5.244365e+00,3.060000e-06,2.111387e-02,4.339755e-02,7.188398e-02,4.261888e+01
Recoveries,67463.0,5.969158e+01,3.570263e+02,3.560000e-05,1.629818e+00,3.344524e+00,5.453727e+00,4.354467e+03
Collection Recovery Fee,67463.0,1.125141e+00,3.489885e+00,3.620000e-05,4.762594e-01,7.801406e-01,1.070566e+00,1.668330e+02
Collection 12 months Medical,67463.0,2.130056e-02,1.443855e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
Last week Pay,67463.0,7.116326e+01,4.331585e+01,0.000000e+00,3.500000e+01,6.800000e+01,1.050000e+02,1.610000e+02
Accounts Delinquent,67463.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Total Collection Amount,67463.0,1.464680e+02,7.443822e+02,1.000000e+00,2.400000e+01,3.600000e+01,4.600000e+01,1.642100e+04
Total Current Balance,67463.0,1.595739e+05,1.390332e+05,6.170000e+02,5.037900e+04,1.183690e+05,2.283750e+05,1.177412e+06
Total Revolving Credit Limit,67463.0,2.312301e+04,2.091670e+04,1.000000e+03,8.155500e+03,1.673300e+04,3.214650e+04,2.011690e+05
Loan Status,67463.0,9.250997e-02,2.897466e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00

In [7]:
df.shape

(67463, 35)

In [8]:
df.isnull().sum()

ID                              0
Loan Amount                     0
Funded Amount                   0
Funded Amount Investor          0
Term                            0
Batch Enrolled                  0
Interest Rate                   0
Grade                           0
Sub Grade                       0
Employment Duration             0
Home Ownership                  0
Verification Status             0
Payment Plan                    0
Loan Title                      0
Debit to Income                 0
Delinquency - two years         0
Inquires - six months           0
Open Account                    0
Public Record                   0
Revolving Balance               0
Revolving Utilities             0
Total Accounts                  0
Initial List Status             0
Total Received Interest         0
Total Received Late Fee         0
Recoveries                      0
Collection Recovery Fee         0
Collection 12 months Medical    0
Application Type                0
Last week Pay                   0
Accounts Delinquent             0
Total Collection Amount         0
Total Current Balance           0
Total Revolving Credit Limit    0
Loan Status                     0
dtype: int64

In [9]:
df=df.drop(["ID","Batch Enrolled","Grade","Sub Grade","Employment Duration","Payment Plan","Public Record","Collection 12 months Medical","Application Type","Last week Pay","Accounts Delinquent","Loan Title"],axis=1)

In [10]:
df["Verification Status"].unique()

array(['Not Verified', 'Source Verified', 'Verified'], dtype=object)

In [11]:
df["Initial List Status"].unique()

array(['w', 'f'], dtype=object)

In [12]:
df=df.replace('Not Verified','0')

In [13]:
df=df.replace('Verified','1')

In [14]:
df=df.replace('Source Verified','2')

In [15]:
df=df.replace('w','0')

In [16]:
df=df.replace('f','1')

In [17]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Loan Amount,67463.0,16848.902776,8367.865726,1014.000000,10012.000000,16073.000000,22106.000000,3.500000e+04
Funded Amount,67463.0,15770.599114,8150.992662,1014.000000,9266.500000,13042.000000,21793.000000,3.499900e+04
Funded Amount Investor,67463.0,14621.799323,6785.345170,1114.590204,9831.684984,12793.682170,17807.594120,3.499975e+04
Term,67463.0,58.173814,3.327441,36.000000,58.000000,59.000000,59.000000,5.900000e+01
Interest Rate,67463.0,11.846258,3.718629,5.320006,9.297147,11.377696,14.193533,2.718235e+01
Home Ownership,67463.0,80541.502522,45029.120366,14573.537170,51689.843335,69335.832680,94623.322785,4.065615e+05
Debit to Income,67463.0,23.299241,8.451824,0.675299,16.756416,22.656658,30.048400,3.962986e+01
Delinquency - two years,67463.0,0.327127,0.800888,0.000000,0.000000,0.000000,0.000000,8.000000e+00
Inquires - six months,67463.0,0.145754,0.473291,0.000000,0.000000,0.000000,0.000000,5.000000e+00
Open Account,67463.0,14.266561,6.225060,2.000000,10.000000,13.000000,16.000000,3.700000e+01
Revolving Balance,67463.0,7699.342425,7836.148190,0.000000,2557.000000,5516.000000,10184.500000,1.169330e+05
Revolving Utilities,67463.0,52.889443,22.539450,0.005172,38.658825,54.082334,69.177117,1.008800e+02
Total Accounts,67463.0,18.627929,8.319246,4.000000,13.000000,18.000000,23.000000,7.200000e+01
Total Received Interest,67463.0,2068.992542,2221.918745,4.736746,570.903814,1330.842771,2656.956837,1.430137e+04
Total Received Late Fee,67463.0,1.143969,5.244365,0.000003,0.021114,0.043398,0.071884,4.261888e+01
Recoveries,67463.0,59.691578,357.026346,0.000036,1.629818,3.344524,5.453727,4.354467e+03
Collection Recovery Fee,67463.0,1.125141,3.489885,0.000036,0.476259,0.780141,1.070566,1.668330e+02
Total Collection Amount,67463.0,146.467990,744.382233,1.000000,24.000000,36.000000,46.000000,1.642100e+04
Total Current Balance,67463.0,159573.933638,139033.245565,617.000000,50379.000000,118369.000000,228375.000000,1.177412e+06
Total Revolving Credit Limit,67463.0,23123.005544,20916.699999,1000.000000,8155.500000,16733.000000,32146.500000,2.011690e+05
Loan Status,67463.0,0.092510,0.289747,0.000000,0.000000,0.000000,0.000000,1.000000e+00

In [18]:
df.nunique()

Loan Amount                     27525
Funded Amount                   24548
Funded Amount Investor          67441
Term                                3
Interest Rate                   67448
Home Ownership                  67454
Verification Status                 3
Debit to Income                 67454
Delinquency - two years             9
Inquires - six months               6
Open Account                       36
Revolving Balance               20582
Revolving Utilities             67458
Total Accounts                     69
Initial List Status                 2
Total Received Interest         67451
Total Received Late Fee         67380
Recoveries                      67387
Collection Recovery Fee         67313
Total Collection Amount          2193
Total Current Balance           60901
Total Revolving Credit Limit    37708
Loan Status                         2
dtype: int64